-- Optimised version of q.sql generated by OpenAI's GPT-5 mini.
--      Output confirmed identical.

COPY (
    WITH 
        xref_1 AS (
            SELECT
                l."Hylak_id"
                    AS hylak_id,
                l."Lake_name"
                    AS lake_name,
                l."Pour_long"
                    AS pour_long,
                l."Pour_lat"
                    AS pour_lat,
                lp."4326_geometry"
                    AS geometry
            FROM 
                lakes l
            JOIN 
                lakes_polys lp
                    ON l."Hylak_id" = lp."Hylak_id"
            GROUP BY 
                l."Hylak_id", 
                l."Lake_name",
                l."Pour_long",
                l."Pour_lat",
                lp."4326_geometry"
        ),
        xref_2 AS (
            SELECT
                id,
                CASE COALESCE("Density", '')
                    WHEN 'Heavy'  THEN 3
                    WHEN 'Medium' THEN 2
                    WHEN 'Light'  THEN 1
                    ELSE 0
                END 
                    AS rank,
                (TO_DATE(SUBSTRING("Start" FROM 1 FOR 7), 'YYYYDDD') + i)::date 
                    AS day,
                geometry
            FROM 
                public.hms_smokes{{YEAR}}
            CROSS JOIN 
                LATERAL generate_series(
                    0,
                    (TO_DATE(SUBSTRING("End" FROM 1 FOR 7), 'YYYYDDD') - TO_DATE(SUBSTRING("Start" FROM 1 FOR 7), 'YYYYDDD'))::int
                ) 
                    AS i
        ),
        xref_3 AS (
            SELECT
                x1.hylak_id,
                x1.lake_name,
                x1.pour_long,
                x1.pour_lat,
                x2.day,
                MAX(x2.rank) 
                    AS rank
            FROM 
                xref_1 x1
            LEFT JOIN 
                xref_2 x2
                    ON ST_Intersects(x1.geometry, x2.geometry)
            GROUP BY
                x1.hylak_id,
                x1.lake_name,
                x1.pour_long,
                x1.pour_lat,
                x2.day
        )
        SELECT
            hylak_id,
            lake_name,
            pour_long,
            pour_lat,
            COUNT(CASE WHEN rank = 1 THEN 1 END) 
                AS "Smoke_days_light_point",
            COUNT(CASE WHEN rank = 2 THEN 1 END) 
                AS "Smoke_days_medium_point",
            COUNT(CASE WHEN rank = 3 THEN 1 END) 
                AS "Smoke_days_heavy_point",
            COUNT(CASE WHEN rank = 0 THEN 1 END) 
                AS "Smoke_days_undefined_point",
            (COUNT(CASE WHEN rank = 1 THEN 1 END)
            + COUNT(CASE WHEN rank = 2 THEN 1 END)
            + COUNT(CASE WHEN rank = 3 THEN 1 END)
            + COUNT(CASE WHEN rank = 0 THEN 1 END)) 
                AS "Smoke_days_aggregate_point"
        FROM 
            xref_3
        GROUP BY 
            hylak_id,
            lake_name,
            pour_long,
            pour_lat
        ORDER BY 
            hylak_id
) TO '/Users/williamchuter-davies/Downloads/wfrtl_composite{{YEAR}}.csv' WITH CSV HEADER;
